apiVersion: v1
kind: Service
metadata:
  name: argocd-service
spec:
  selector:
    app: argocd # Selects pods to expose via the Service
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the Service
      targetPort: 80 # Port on which the pods are listening
  type: LoadBalancer # Exposes the Service externally using a cloud load balancer
